// here's a big thing of sample data for the grid

const Data = [
  {
    key: 0,
    alignment: 'Neutral',
    background: 'Guild Artisan',
    charClass: 'Wizard 1',
    race: 'Rock Gnome',
    name: 'Felliwin Pollyrhom Goldiwick',
  },
  {
    key: 1,
    alignment: 'Chaotic Good',
    background: 'Criminal (custom)',
    charClass: 'Barbarian 8',
    race: 'High Elf',
    name: 'Pancho �El Hombre de los Herramientos�\nVillalobo de la Plaza de Sufrimeiento',
  },
  {
    key: 2,
    alignment: 'Chaotic Evil',
    background: 'Hermit (custom)',
    charClass: 'Paladin 1',
    race: 'Drow Elf',
    name: "Thallescenda De'Rujan",
  },
  {
    key: 3,
    alignment: 'Neutral',
    background: 'Urchin',
    charClass: 'Monk 4',
    race: 'Tiefling',
    name: 'Tina',
  },
  {
    key: 4,
    alignment: 'Neutral (mostly) Good',
    background: 'Soldier',
    charClass: 'Monk 1',
    race: 'Stout Halfling',
    name: 'Rellion Tadfoot',
  },
  {
    key: 5,
    alignment: 'Neutral Good',
    background: 'Noble',
    charClass: 'Cleric 1',
    race: 'Tiefling',
    name: 'Vollena Belle Mor-Kallis',
  },
  {
    key: 6,
    alignment: 'Chaotic Evil',
    background: 'Acolyte',
    charClass: 'Warlock 1',
    race: 'Half-Orc',
    name: 'Grogt Trugah',
  },
  {
    key: 7,
    alignment: 'Neutral',
    background: 'Entertainer (Gladiator)',
    charClass: 'Fighter 1',
    race: 'Half-Elf',
    name: 'Rubahh "Ruby" Lisica',
  },
  {
    key: 8,
    alignment: 'Neutral',
    background: 'Sailor',
    charClass: 'Druid 1',
    race: 'Half-Elf',
    name: 'Bellana Seawalker',
  },
  {
    key: 9,
    alignment: 'Chaotic Good',
    background: 'Criminal',
    charClass: 'Bard 1',
    race: 'Half-Elf',
    name: 'Dinalla',
  },
  {
    key: 10,
    alignment: 'Lawful Good',
    background: 'Guild Artisan',
    charClass: 'Fighter 1',
    race: 'Tiefling',
    name: 'Determination',
  },
  {
    key: 11,
    alignment: 'Neutral Good',
    background: 'Folk Hero',
    charClass: 'Fighter 1',
    race: 'Hill Dwarf',
    name: 'Agnathus Bluestone',
  },
  {
    key: 12,
    alignment: 'Neutral',
    background: 'Guild Merchant',
    charClass: 'Sorcerer 1',
    race: 'Human',
    name: 'Ivan Igerson',
  },
  {
    key: 13,
    alignment: 'Chaotic Neutral',
    background: 'Charlatan',
    charClass: 'Bard 1',
    race: 'Stout Halfling',
    name: 'Phillipa Thessalonica',
  },
  {
    key: 14,
    alignment: 'Lawful Good',
    background: 'Criminal: Spy',
    charClass: 'Rogue 1',
    race: 'Hill Dwarf',
    name: 'Dorfog',
  },
  {
    key: 15,
    alignment: null,
    background: 'Guild Artisan',
    charClass: 'Rogue 1',
    race: 'Forest Gnome',
    name: 'Sulfika Cerinth Dragonwort Sulpher Murnig',
  },
  {
    key: 16,
    alignment: 'Neutral Good',
    background: 'Sage (librarian)',
    charClass: 'Warlock1',
    race: 'Tiefling',
    name: 'Kinais Yysverum',
  },
  {
    key: 17,
    alignment: 'Neutral Good',
    background: 'Outlander',
    charClass: 'Druid 1',
    race: 'Forest Gnome',
    name: 'Gekgek Abernathy Birdfinger Yam Timberfall',
  },
  {
    key: 18,
    alignment: 'Chaotic Neutral',
    background: 'charlaton',
    charClass: 'Sorcerer 1',
    race: 'Forest Gnome',
    name: 'Namfoodle the Fidlatastic',
  },
  {
    key: 19,
    alignment: 'Neutral Evil',
    background: 'Criminal',
    charClass: 'Sorcerer 1',
    race: 'Drow Elf',
    name: 'Quilvine Blackblood',
  },
  {
    key: 20,
    alignment: 'Chaotic Good',
    background: 'Sailor',
    charClass: 'Cleric 1',
    race: 'Hill Dwarf',
    name: 'Thalla Seafoam',
  },
  {
    key: 21,
    alignment: 'Neutral',
    background: 'Information Dealer',
    charClass: 'Rogue 1',
    race: 'Lightfoot Halfling',
    name: 'Plumpuri Bryndlewythe',
  },
  {
    key: 22,
    alignment: 'Neutral',
    background: 'Urchin',
    charClass: 'Monk 1',
    race: 'Half-Elf',
    name: 'Fen "Long Legs" Tyfen',
  },
  {
    key: 23,
    alignment: 'Lawful Neutral',
    background: 'Sage',
    charClass: 'Warlock 1',
    race: 'Duergar Dwarf',
    name: 'Kirassa Gurkeld',
  },
  {
    key: 24,
    alignment: 'Chaotic Good',
    background: 'Noble',
    charClass: 'Paladin 1',
    race: 'gold Dragonborn',
    name: 'Tarhun Linxakasendalor',
  },
  {
    key: 25,
    alignment: 'Lawful Neutral',
    background: 'Outlander',
    charClass: 'Fighter 1',
    race: 'Wood Elf',
    name: 'Geherit Greymar',
  },
  {
    key: 26,
    alignment: 'Neutral Good',
    background: 'Noble',
    charClass: 'Paladin 4',
    race: 'Half-Orc',
    name: 'Lyle Milo Greenbottle',
  },
  {
    key: 27,
    alignment: null,
    background: null,
    charClass: 'Wizard 1',
    race: 'Hill Dwarf',
    name: 'Grenda Stonemaker',
  },
  {
    key: 28,
    alignment: 'Neutral',
    background: 'Urchin',
    charClass: 'Monk 1',
    race: 'Tiefling',
    name: 'Tina',
  },
  {
    key: 29,
    alignment: 'Neutral Good',
    background: 'Sailor',
    charClass: 'Barbarian 1',
    race: 'Half-Orc',
    name: 'Arvid Isak Shipborn',
  },
  {
    key: 30,
    alignment: 'Neutral Good',
    background: 'Folk Hero',
    charClass: 'Ranger 1',
    race: 'Stout Halfling',
    name: 'Tova Angelbane',
  },
  {
    key: 31,
    alignment: 'Chaotic Neutral',
    background: 'Charlatan',
    charClass: 'Bard 1',
    race: 'Human',
    name: 'Charessa Reilly',
  },
  {
    key: 32,
    alignment: 'LG',
    background: 'Noble',
    charClass: 'Rogue 1',
    race: 'High Elf',
    name: 'Tiffany Toforiomanahmanaxolotlbeinget',
  },
  {
    key: 33,
    alignment: 'Neutral Good',
    background: 'Outlander',
    charClass: 'Ranger 1',
    race: 'Human',
    name: 'Chennen Genseldotter',
  },
  {
    key: 34,
    alignment: 'Lawful Neutral',
    background: 'Investigator',
    charClass: 'Wizard 1',
    race: 'Stout Halfling',
    name: 'Lois Everheart',
  },
  {
    key: 35,
    alignment: 'Lawful Neutral',
    background: 'Guild Artisan',
    charClass: 'Wizard 1',
    race: 'Half-Orc',
    name: 'Kurzil Turtlebridge',
  },
  {
    key: 36,
    alignment: 'Neutral Good',
    background: 'Urchin',
    charClass: 'Ranger 1',
    race: 'Half-Elf',
    name: 'Delan Ashhands',
  },
  {
    key: 37,
    alignment: 'Chaotic Neutral',
    background: 'Urchin',
    charClass: 'Paladin 1',
    race: 'Human',
    name: 'Chondrek',
  },
  {
    key: 38,
    alignment: 'Lawful Good',
    background: 'Noble',
    charClass: 'Cleric 1',
    race: 'Human',
    name: 'Don Jeronimo',
  },
  {
    key: 39,
    alignment: 'Chaotic Good',
    background: 'Noble',
    charClass: 'Barbarian 1',
    race: 'blue Dragonborn',
    name: 'Ursundra Kirtaketh',
  },
  {
    key: 40,
    alignment: 'Lawful Good',
    background: 'Professional Spy',
    charClass: 'Bard 1',
    race: 'Hill Dwarf',
    name: 'Ironhide Cliffjumper',
  },
  {
    key: 41,
    alignment: 'Lawful Good',
    background: 'Sage',
    charClass: 'Wizard 1',
    race: 'Dragonborn',
    name: 'Nadash Silomen',
  },
  {
    key: 42,
    alignment: 'Neutral',
    background: 'Noble',
    charClass: 'Monk 1',
    race: 'blue Dragonborn',
    name: 'Prakashth Llewesken Krevath',
  },
  {
    key: 43,
    alignment: 'Neutral Good',
    background: 'Hermit',
    charClass: 'Sorcerer 1',
    race: 'White Dragonborn',
    name: 'Ankara Sukhothai',
  },
  {
    key: 44,
    alignment: 'Neutral Good',
    background: 'Noble',
    charClass: 'Cleric 1',
    race: 'Half-Elf',
    name: 'Celes Tiana Morogrov',
  },
  {
    key: 45,
    alignment: 'Neutral Good',
    background: 'Charlatan',
    charClass: 'Rogue 1',
    race: 'Human',
    name: 'Herrith Reizhand',
  },
  {
    key: 46,
    alignment: 'Lawful Good',
    background: 'Outlander',
    charClass: 'Barbarian 1',
    race: 'Mountain Dwarf',
    name: 'Grallic Godstone',
  },
  {
    key: 47,
    alignment: 'Neutral',
    background: 'Explorer',
    charClass: 'Ranger 1',
    race: 'Forest Gnome',
    name: 'Ellyrow Murnigow "Mossbutt"',
  },
  {
    key: 48,
    alignment: 'Neutral Good',
    background: 'Noble',
    charClass: 'Paladin 1',
    race: 'Half-Orc',
    name: 'Lyle Milo Greenbottle',
  },
  {
    key: 49,
    alignment: 'Neutral (goodish)',
    background: 'Sailor',
    charClass: 'Cleric 1',
    race: 'Dragonborn',
    name: 'Ajahz al Dekrathi',
  },
  {
    key: 50,
    alignment: 'Neutral',
    background: 'Noble',
    charClass: 'Druid 1',
    race: 'Tiefling',
    name: 'Armara Temerity Hennick',
  },
  {
    key: 51,
    alignment: 'Neutral',
    background: 'Guild Artisan',
    charClass: 'Warlock 1',
    race: 'Rock Gnome',
    name: 'Daedalus',
  },
  {
    key: 52,
    alignment: 'Chaotic Good',
    background: 'Criminal (custom)',
    charClass: 'Barbarian 1',
    race: 'High Elf',
    name: 'Pancho �El Hombre de los Herramientos�\nVillalobo de la Plaza de Sufrimeiento',
  },
  {
    key: 53,
    alignment: 'Neutral Good',
    background: 'Hunter-killer',
    charClass: 'Ranger 1',
    race: 'Wood Elf',
    name: 'Penelope Arkalashan',
  },
  {
    key: 54,
    alignment: 'Neutral Good',
    background: 'Explorer',
    charClass: 'Sorcerer 1',
    race: 'Lightfoot Halfling',
    name: 'Billdrup Willowdeep',
  },
  {
    key: 55,
    alignment: 'Neutral',
    background: 'Noble',
    charClass: 'Barbarian 1',
    race: 'Half-Elf',
    name: 'Aurelius "Gloomkin" Turelliano',
  },
  {
    key: 56,
    alignment: 'Neutral Good',
    background: 'Monastic',
    charClass: 'Monk 1',
    race: 'Rock Gnome',
    name: 'Knockliddle Chirrup',
  },
  {
    key: 57,
    alignment: 'Neutral Good',
    background: 'Folk Hero',
    charClass: 'Druid 1',
    race: 'Lightfoot Halfling',
    name: 'Garfield Hacket',
  },
  {
    key: 58,
    alignment: 'Lawful Evil',
    background: 'Soldier',
    charClass: 'Cleric 1',
    race: 'Tiefling',
    name: 'Grick Faithhammer',
  },
  {
    key: 59,
    alignment: 'Neutral Good',
    background: 'Soldier',
    charClass: 'Bard 1',
    race: 'Half-Orc',
    name: 'Jopnil Hinseewoh',
  },
  {
    key: 60,
    alignment: 'Lawful Neutral',
    background: 'Guild Artisan',
    charClass: 'Wizard 1',
    race: 'Tiefling',
    name: 'Prosperity',
  },
  {
    key: 61,
    alignment: 'Neutral Good',
    background: 'Unchosen',
    charClass: 'Fighter 1',
    race: 'Forest Gnome',
    name: 'Gerbelle Booknoodle Janjimble',
  },
  {
    key: 62,
    alignment: 'Neutral Good',
    background: 'Noble',
    charClass: 'Paladin 5',
    race: 'Half-Orc',
    name: 'Lyle Milo Greenbottle',
  },
];

export default Data;
